- code: "PRMTR001"
  description: "custom"
  message: "Document named '{documentTitle}' contains invalid project parameters. Details: \n\n{details} \n\nExecution time '{duration}' ms."
  severity: "Message"
  isActive: false
  take: "!property('IsFamilyDocument')"
  parameters:
    - guid: "dd002437-b54b-41b5-9142-71704a513ef3"
      name: "CUBE_ID"
      # Revit 2024 and newer. For Revit 2021-2023 use a BuiltInParameterGroup name such as "PG_TEXT".
      group: "autodesk.parameter.group:text-1.0.0"
      isInstance: true
      categories: ["OST_DuctCurves"]
      allowVaryBetweenGroups: true
    - guid: "2f60ce79-f71b-4b1e-9b74-7ce425cf3cec"
      name: "CUBE_Зависимости"
      group: "autodesk.parameter.group:text-1.0.0"
      isInstance: true
      categories: ["-2008000"]
      allowVaryBetweenGroups: true
    - name: "Какой-то параметр"
      group: "autodesk.parameter.group:text-1.0.0"
      isInstance: true
      categories: ["-2008000"]
      allowVaryBetweenGroups: true
