<Project Sdk="VolocyNazad.Revit.Sdk/1.0.44">
	<PropertyGroup>
		<UseWPF>true</UseWPF>
	</PropertyGroup>
	<ItemGroup>
	  <PackageVersion Update="SonarAnalyzer.CSharp" Version="10.34.0.3385" />
	</ItemGroup>
	<ItemGroup>
	  <PackageReference Update="SonarAnalyzer.CSharp">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
	  </PackageReference>
	</ItemGroup>
</Project>
