<Project Sdk="VolocyNazad.Revit.Sdk/1.0.43">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Nice3point.TUnit.Revit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Revit.Linter.ElementDependencyDefiners\Revit.Linter.ElementDependencyDefiners.csproj" />
  </ItemGroup>
</Project>
