<Project Sdk="VolocyNazad.Revit.Sdk/1.0.43">
	<PropertyGroup>
		<UseWPF>true</UseWPF>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="MaterialDesignThemes" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Localization" />
		<PackageReference Include="Revit_All_Main_Versions_API_x64" />
		<PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" />
		<PackageReference Include="CommunityToolkit.Mvvm" />
		<PackageReference Include="VolocyNazad.MVVM.DependencyInjection" />
		<PackageReference Include="XamlConstructor">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="VolocyNazad.Revit.Context" />
	</ItemGroup>
	<ItemGroup>
		<EmbeddedResource Remove="ViewModels\DialogViewModel*.resx" />
		<None Include="ViewModels\DialogViewModel.resx"><DependentUpon>DialogViewModel.cs</DependentUpon></None>
		<None Include="ViewModels\DialogViewModel.ru-RU.resx"><DependentUpon>DialogViewModel.cs</DependentUpon></None>
		<AdditionalFiles Include="ViewModels\DialogViewModel.resx" />
		<EmbeddedResource Remove="ViewModels\ConfirmationDialogViewModel*.resx" />
		<None Include="ViewModels\ConfirmationDialogViewModel.resx"><DependentUpon>ConfirmationDialogViewModel.cs</DependentUpon></None>
		<None Include="ViewModels\ConfirmationDialogViewModel.ru-RU.resx"><DependentUpon>ConfirmationDialogViewModel.cs</DependentUpon></None>
		<AdditionalFiles Include="ViewModels\ConfirmationDialogViewModel.resx" />
		<ProjectReference Include="..\Revit.Linter.Localization.Generator\Revit.Linter.Localization.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Revit.Linter.ThemeManaging\Revit.Linter.ThemeManaging.csproj" />
		<ProjectReference Include="..\Revit.Linter.Localization\Revit.Linter.Localization.csproj" />
	</ItemGroup>

</Project>
