<Project Sdk="VolocyNazad.Revit.Sdk/1.0.43">
	<PropertyGroup>
		<UseWPF>true</UseWPF>
	</PropertyGroup>
	<ItemGroup>
		<EmbeddedResource Remove="ViewModels\DiagnosticListViewModel*.resx" />
		<None Include="ViewModels\DiagnosticListViewModel.resx"><DependentUpon>DiagnosticListViewModel.cs</DependentUpon></None>
		<None Include="ViewModels\DiagnosticListViewModel.ru-RU.resx"><DependentUpon>DiagnosticListViewModel.cs</DependentUpon></None>
		<AdditionalFiles Include="ViewModels\DiagnosticListViewModel.resx" />
		<ProjectReference Include="..\Revit.Linter.Localization.Generator\Revit.Linter.Localization.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="MaterialDesignThemes" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Localization" />
		<PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" />
		<PackageReference Include="Revit_All_Main_Versions_API_x64" />
		<PackageReference Include="VolocyNazad.MVVM.DependencyInjection" />
		<PackageReference Include="CommunityToolkit.Mvvm" />
		<PackageReference Include="XamlConstructor">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Revit.Linter.Core\Revit.Linter.Core.csproj" />
		<ProjectReference Include="..\Revit.Linter.Localization\Revit.Linter.Localization.csproj" />
		<ProjectReference Include="..\Revit.Linter.RunDiagnosticPresenter\Revit.Linter.RunDiagnosticPresenter.csproj" />
		<ProjectReference Include="..\Revit.Linter.ThemeManaging\Revit.Linter.ThemeManaging.csproj" />
	</ItemGroup>
</Project>
