using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Text;
using System.Xml.Linq;

namespace Revit.Linter.Localization.Generator;

[Generator]
public sealed class LocalizationPropertiesGenerator : IIncrementalGenerator
{
    private const string AttributeName = "Revit.Linter.Localization.GenerateLocalizedPropertiesAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(output => output.AddSource(
            "GenerateLocalizedPropertiesAttribute.g.cs",
            SourceText.From(AttributeSource, Encoding.UTF8)));

        IncrementalValuesProvider<INamedTypeSymbol> viewModels = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeName,
                static (node, _) => node is ClassDeclarationSyntax,
                static (syntaxContext, _) => (INamedTypeSymbol)syntaxContext.TargetSymbol);

        IncrementalValueProvider<ImmutableArray<ResourceFile>> resources = context.AdditionalTextsProvider
            .Where(static file => IsNeutralResource(file.Path))
            .Select(static (file, cancellationToken) => ReadResource(file, cancellationToken))
            .Where(static resource => resource is not null)
            .Select(static (resource, _) => resource!)
            .Collect();

        context.RegisterSourceOutput(viewModels.Combine(resources), static (output, value) =>
        {
            INamedTypeSymbol viewModel = value.Left;
            ResourceFile? resource = value.Right.FirstOrDefault(item =>
                string.Equals(item.ClassName, viewModel.Name, StringComparison.Ordinal));
            if (resource is null) return;

            output.AddSource($"{viewModel.ToDisplayString().Replace('.', '_')}.Localization.g.cs",
                SourceText.From(GenerateSource(viewModel, resource), Encoding.UTF8));
        });
    }

    private static bool IsNeutralResource(string path)
    {
        if (!path.EndsWith(".resx", StringComparison.OrdinalIgnoreCase)) return false;
        string name = Path.GetFileNameWithoutExtension(path);
        int separator = name.LastIndexOf('.');
        return separator < 0 || name.Length - separator - 1 is not (2 or 5);
    }

    private static ResourceFile? ReadResource(AdditionalText file, CancellationToken cancellationToken)
    {
        SourceText? text = file.GetText(cancellationToken);
        if (text is null) return null;

        XDocument document = XDocument.Parse(text.ToString());
        ImmutableArray<string> keys = document.Root?.Elements("data")
            .Select(element => element.Attribute("name")?.Value)
            .Where(static key => !string.IsNullOrWhiteSpace(key))
            .Select(static key => key!)
            .ToImmutableArray() ?? ImmutableArray<string>.Empty;
        return new(Path.GetFileNameWithoutExtension(file.Path), keys);
    }

    private static string GenerateSource(INamedTypeSymbol type, ResourceFile resource)
    {
        string namespaceName = type.ContainingNamespace.ToDisplayString();
        string resourceBaseName = $"{namespaceName}.{type.Name}";
        const string rootNamespace = "Revit.Linter.";
        string localizerBaseName = resourceBaseName.StartsWith(rootNamespace, StringComparison.Ordinal)
            ? resourceBaseName.Substring(rootNamespace.Length)
            : resourceBaseName;
        StringBuilder source = new($$"""
            // <auto-generated />
            #nullable enable
            namespace {{namespaceName}};

            partial class {{type.Name}}
            {
                private static string GetLocalizedString(string key, params object[] arguments)
                {
                    string value = global::Revit.Linter.Localization.LocalizationResourceReader.GetString(
                        "Revit.Linter.Localization.{{localizerBaseName}}", key);
                    return arguments.Length == 0
                        ? value
                        : string.Format(global::System.Globalization.CultureInfo.CurrentCulture, value, arguments);
                }

            """);

        foreach (string key in resource.Keys)
            source.Append("    public string ").Append(ToPropertyName(key))
                .Append(" => GetLocalizedString(\"").Append(Escape(key)).AppendLine("\");");

        source.AppendLine("}");
        return source.ToString();
    }

    private static string ToPropertyName(string key)
    {
        StringBuilder result = new();
        bool upper = true;
        foreach (char character in key)
        {
            if (!char.IsLetterOrDigit(character))
            {
                upper = true;
                continue;
            }

            result.Append(upper ? char.ToUpperInvariant(character) : character);
            upper = false;
        }
        return result.ToString();
    }

    private static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private sealed record ResourceFile(string ClassName, ImmutableArray<string> Keys);

    private const string AttributeSource = """
        // <auto-generated />
        namespace Revit.Linter.Localization
        {
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false)]
            internal sealed class GenerateLocalizedPropertiesAttribute : global::System.Attribute
            {
            }
        }
        """;
}
