<Project Sdk="VolocyNazad.Revit.Sdk/1.0.43">

	<ItemGroup>
		<PackageReference Include="Revit_All_Main_Versions_API_x64" />
		<PackageReference Include="VolocyNazad.Revit.TransactionMemoryCache" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Toolkit.Revit.Extensions\Toolkit.Revit.Extensions.csproj" />
	</ItemGroup>

</Project>
